version: '2'
services:
    phppra:
        build:
            context: ./PhpPra/
        volumes:
            - ./PhpPra/src:/var/www/html
        ports:
            - 8081:8081
    postgres:
        build:
            context: ./Postgres
        volumes:
            - ./Postgres/init.d:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432
    laravelapp:
        build:
            context: ./LaravelApp/
        volumes:
            - ./LaravelApp/src:/var/www/html
        ports:
            - 8082:8082
    codeigniterapp:
        build:
            context: ./CodeIgniterApp/
        volumes:
            - ./CodeIgniterApp/src:/var/www/html
        ports:
            - 8083:8083
